### ISSUE TITLE
errors with js file. help.

### ISSUE THREAD

**Issue by RalkeyOfficial** [2dareis2do/ticker-type-text#1]
Uncaught TypeError: contents[(count % contents.length)] is undefined on line 99

![image](https://user-images.githubusercontent.com/30209145/151768846-efdb0d20-7e7e-44d9-94d2-e71c636ed4c0.png)

along with this error

![image](https://user-images.githubusercontent.com/30209145/151770363-782871bb-84a0-43f7-a689-7e0a86dfd92c.png)

i have the dependencie installed and did everything per manual
so i dont understand why its giving an error

**Comment by 2dareis2do** [comment]
Working demo here:

https://dev.danlobo.co.uk/textticker/index.html

Collection is selected like so. e.g.

`let $elements = $(".tt-holder .tt");`

example here: https://github.com/2dareis2do/ticker-type-text/blob/master/demo/js/script.js 

Not sure but I would first check that your jquery collection of items is being selected properly as failure to do so could lead to undefined error. 

if you have a demo I would be happy to look at further.

**Comment by RalkeyOfficial** [comment]
i got the correct item collection code according to the docs.


// tickerText(contents, keep, seconds, delay = 20, iterations = 0, ratio, secondsout, dev = false, pausetarget, stoptarget);

let $elements = $(".tt-holder .tt");

let animatetext = function () {
    $(".ttt").tickerText($elements, 16, 3, 100, 1, 0.5, 2, false, "timerpause", "timerstop");
};
$(animatetext);


here is the project i am working on:

https://github.com/RalkeyOfficial/portofolio/tree/main/V2

maybe you see something i dont.

**Comment by 2dareis2do** [comment]
ok, had a quick look.

Couple of things:

1. You need an element to target the ticker text e.g.  `<h1 class="ttt" id="target"></h1>`
2. You need to wrap your script in a document ready:

e.g. 

```
$(document).ready(function () {
    let $elements = $(".tt-holder .tt");
    let animatetext = function () {
    // tickerText(contents, keep, seconds, delay = 20, iterations = 0, ratio, secondsout, dev = false, pausetarget, stoptarget);
        $(".ttt").tickerText($elements, 6, 3, 100, 1, 0.5, 2, false, "timerpause", "timerstop");

    };
 
    $(animatetext);

});
```

**Comment by RalkeyOfficial** [comment]
that worked thank you
